-- Initial GGcrafter schema. Normally generated and applied with `npm run db:migrate`.
CREATE TABLE "User" ("id" TEXT NOT NULL,"telegramId" BIGINT NOT NULL,"username" TEXT,"displayName" TEXT NOT NULL,"avatarUrl" TEXT,"balance" INTEGER NOT NULL DEFAULT 1250,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Skin" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"price" INTEGER NOT NULL,"imageUrl" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"rarity" TEXT NOT NULL DEFAULT 'Common',"active" BOOLEAN NOT NULL DEFAULT true,"craftEnabled" BOOLEAN NOT NULL DEFAULT true,"craftWeight" INTEGER NOT NULL DEFAULT 100,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Skin_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Inventory" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"skinId" TEXT NOT NULL,"obtainedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Inventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PromoCode" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"reward" INTEGER NOT NULL,"usageLimit" INTEGER NOT NULL,"usesCount" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoCode_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PromoCodeUse" ("id" TEXT NOT NULL,"promoId" TEXT NOT NULL,"userId" TEXT NOT NULL,"usedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoCodeUse_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CraftHistory" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"usedSkinIds" TEXT[],"resultSkinId" TEXT NOT NULL,"inputValue" INTEGER NOT NULL,"resultValue" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CraftHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RequestLock" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RequestLock_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_telegramId_key" ON "User"("telegramId"); CREATE UNIQUE INDEX "Skin_name_key" ON "Skin"("name"); CREATE UNIQUE INDEX "PromoCode_code_key" ON "PromoCode"("code"); CREATE UNIQUE INDEX "PromoCodeUse_promoId_userId_key" ON "PromoCodeUse"("promoId","userId");
CREATE INDEX "Inventory_userId_idx" ON "Inventory"("userId"); CREATE INDEX "CraftHistory_userId_idx" ON "CraftHistory"("userId"); CREATE INDEX "RequestLock_createdAt_idx" ON "RequestLock"("createdAt");
ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_skinId_fkey" FOREIGN KEY ("skinId") REFERENCES "Skin"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "PromoCodeUse" ADD CONSTRAINT "PromoCodeUse_promoId_fkey" FOREIGN KEY ("promoId") REFERENCES "PromoCode"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PromoCodeUse" ADD CONSTRAINT "PromoCodeUse_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CraftHistory" ADD CONSTRAINT "CraftHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CraftHistory" ADD CONSTRAINT "CraftHistory_resultSkinId_fkey" FOREIGN KEY ("resultSkinId") REFERENCES "Skin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
