import React, {useEffect, useState} from 'react'; import {createRoot} from 'react-dom/client'; import './styles.css';
declare global {interface Window {Telegram?: any}}
type Skin={id:string;name:string;price:number;imageUrl:string;rarity:string;description?:string;active?:boolean;craftEnabled?:boolean;craftWeight?:number}; type Item={id:string;skin:Skin}; type User={displayName:string;username?:string;avatarUrl?:string;balance:number};
const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const apiBase=(import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
const demoMode=import.meta.env.VITE_DEMO_MODE==='true';
const key=()=>crypto.randomUUID();
type DemoState={user:User;inventory:Item[];skins:Skin[];promos:any[];uses:string[]};
const starter:Skin[]=[{id:'s1',name:'Neon Phantom',price:35,imageUrl:'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=500&q=80',rarity:'Rare',craftWeight:100},{id:'s2',name:'Azure Strike',price:48,imageUrl:'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80',rarity:'Uncommon',craftWeight:100},{id:'s3',name:'Night Pixel',price:26,imageUrl:'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=500&q=80',rarity:'Common',craftWeight:100},{id:'s4',name:'Gold Circuit',price:62,imageUrl:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=500&q=80',rarity:'Epic',craftWeight:70},{id:'s5',name:'Royal Core',price:130,imageUrl:'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=500&q=80',rarity:'Legendary',craftWeight:20}];
function demoState():DemoState{const saved=localStorage.getItem('ggcrafter-demo');if(saved)return JSON.parse(saved);const state:DemoState={user:{displayName:'Demo Player',username:'demo_player',balance:1250},skins:starter.map(s=>({...s,active:true,craftEnabled:true})),inventory:starter.slice(0,3).map((skin,i)=>({id:`i${i}`,skin})),promos:[{id:'p1',code:'GPT',reward:50,usageLimit:100000,usesCount:0,active:true}],uses:[]};saveDemo(state);return state}
function saveDemo(state:DemoState){localStorage.setItem('ggcrafter-demo',JSON.stringify(state))}
async function mockApi(path:string,opts:RequestInit={},token?:string){const state=demoState(), body=opts.body?JSON.parse(String(opts.body)):{};const save=()=>saveDemo(state);if(path==='/api/me')return {user:state.user,inventory:state.inventory};if(path==='/api/skins')return state.skins.filter(s=>s.active);if(path==='/api/admin/login'){if(body.password!=='6725')throw Error('Неверный пароль');return {token:'demo-admin'}};if(path.startsWith('/api/admin')&&token!=='demo-admin')throw Error('Admin access required');if(path==='/api/promo/redeem'){const p=state.promos.find(p=>p.code===String(body.code).trim().toUpperCase());if(!p||!p.active||p.usesCount>=p.usageLimit)throw Error('Промокод недоступен');if(state.uses.includes(p.id))throw Error('Вы уже использовали этот промокод');p.usesCount++;state.uses.push(p.id);state.user.balance+=p.reward;save();return {user:state.user}}if(path.startsWith('/api/inventory/')&&path.endsWith('/sell')){const id=path.split('/')[3],idx=state.inventory.findIndex(x=>x.id===id);if(idx<0)throw Error('Предмет не найден');state.user.balance+=state.inventory[idx].skin.price;state.inventory.splice(idx,1);save();return {user:state.user}}if(path==='/api/craft'){const ids:string[]=body.inventoryIds||[];if(ids.length<3||ids.length>6)throw Error('Выберите от 3 до 6 предметов');const used=state.inventory.filter(x=>ids.includes(x.id));if(used.length!==ids.length)throw Error('Предмет уже недоступен');const inputValue=used.reduce((a,x)=>a+x.skin.price,0),min=Math.round(inputValue*.365),max=Math.round(inputValue*1.355),choices=state.skins.filter(s=>s.active&&s.craftEnabled&&s.price>=min&&s.price<=max);if(!choices.length)throw Error('Нет подходящего результата');const total=choices.reduce((a,s)=>a+(s.craftWeight||100),0);let roll=Math.random()*total;const skin=choices.find(s=>(roll-=(s.craftWeight||100))<=0)||choices[0];state.inventory=state.inventory.filter(x=>!ids.includes(x.id));const item={id:key(),skin};state.inventory.unshift(item);save();return {item,inputValue,min,max}}if(path==='/api/admin/skins'&&opts.method==='GET')return state.skins;if(path==='/api/admin/skins'&&opts.method==='POST'){const skin={...body,id:key()};state.skins.unshift(skin);save();return skin}if(path.startsWith('/api/admin/skins/')&&opts.method==='PATCH'){const skin=state.skins.find(s=>s.id===path.split('/')[4]);if(!skin)throw Error('Скин не найден');Object.assign(skin,body);save();return skin}if(path==='/api/admin/promos'&&opts.method==='GET')return state.promos;if(path==='/api/admin/promos'&&opts.method==='POST'){const promo={...body,id:key(),usesCount:0};state.promos.unshift(promo);save();return promo}throw Error('Неизвестная demo-операция')}
async function api(path:string, opts:RequestInit={}, token?:string){if(demoMode)return mockApi(path,opts,token);const headers:any={'Content-Type':'application/json',...(opts.headers||{}),'x-telegram-init-data':tg?.initData||''};if(token)headers.Authorization=`Bearer ${token}`;if(opts.method && opts.method!=='GET')headers['Idempotency-Key']=key();const r=await fetch(`${apiBase}${path}`,{...opts,headers});const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка запроса');return d}
function Price({value}:{value:number}){return <span className="coin">🪙 {value.toLocaleString('ru-RU')}</span>}
function App(){const [user,setUser]=useState<User|null>(null),[inventory,setInventory]=useState<Item[]>([]),[skins,setSkins]=useState<Skin[]>([]),[tab,setTab]=useState<'craft'|'market'|'profile'|'admin'>('craft'),[selected,setSelected]=useState<string[]>([]),[result,setResult]=useState<Item|null>(null),[busy,setBusy]=useState(false),[modal,setModal]=useState<string|null>(null),[notice,setNotice]=useState(''),[adminToken,setAdminToken]=useState('');
 const load=async()=>{try{const me=await api('/api/me');setUser(me.user);setInventory(me.inventory);setSkins(await api('/api/skins'));}catch(e:any){setNotice(e.message)}};useEffect(()=>{load()},[]);
 const chosen=inventory.filter(x=>selected.includes(x.id));const value=chosen.reduce((s,x)=>s+x.skin.price,0);const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(i=>i!==id):x.length<6?[...x,id]:x);
 async function craft(){if(selected.length<3)return;setBusy(true);setResult(null);try{const r=await api('/api/craft',{method:'POST',body:JSON.stringify({inventoryIds:selected})});await new Promise(x=>setTimeout(x,1250));setResult(r.item);setSelected([]);await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function sell(id:string){try{await api(`/api/inventory/${id}/sell`,{method:'POST'});await load()}catch(e:any){setNotice(e.message)}}
 return <main><header><button className="brand" onClick={()=>setTab('craft')}><b>GG</b><span>crafter</span></button><div className="header-actions"><Price value={user?.balance||0}/><button onClick={()=>setModal('wallet')} aria-label="Кошелёк">◈</button><button onClick={()=>setTab('profile')} aria-label="Профиль">◉</button></div></header>
 {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}
 {tab==='craft'&&<section className="screen craft"><div className="hero"><p>CRAFT LAB</p><h1>Создай свой <em>GG</em> момент</h1><small>Выберите от 3 до 6 предметов из инвентаря</small></div><div className={'craft-core '+(busy?'spinning':'')}><div className="slots">{[0,1,2,3,4,5].map((_,i)=><div className={'slot '+(chosen[i]?'filled':'')} key={i}>{chosen[i]?<img src={chosen[i].skin.imageUrl}/>:<span>+</span>}</div>)}</div><div className="gg">GG</div></div><div className="craft-card"><div><span>Стоимость крафта</span><Price value={value}/></div><div><span>Диапазон результата</span><strong>{value?`${Math.round(value*.365)} — ${Math.round(value*1.355)}`:'—'} 🪙</strong></div><button className="primary" disabled={selected.length<3||busy} onClick={craft}>{busy?'КРАФТ ИДЁТ...':'ЗАПУСТИТЬ КРАФТ'}</button></div>{result&&<div className="win"><img src={result.skin.imageUrl}/><div><small>ВЫ ВЫИГРАЛИ</small><h3>{result.skin.name}</h3><Price value={result.skin.price}/></div></div>}<Inventory items={inventory} selected={selected} toggle={toggle}/></section>}
 {tab==='market'&&<section className="screen"><h2>Маркет</h2><p className="muted">Каталог пополняется из админ-панели.</p><div className="grid">{skins.map(s=><SkinCard key={s.id} skin={s}/>)}</div></section>}
 {tab==='profile'&&<Profile user={user} items={inventory} sell={sell} notice={setNotice} promo={async code=>{try{await api('/api/promo/redeem',{method:'POST',body:JSON.stringify({code})});setNotice('Промокод активирован');load()}catch(e:any){setNotice(e.message)}}} wallet={()=>setModal('wallet')} admin={()=>setModal('admin')}/>} 
 {tab==='admin'&&<Admin token={adminToken} close={()=>setTab('profile')} reload={load} notice={setNotice}/>} 
 <nav><button className={tab==='craft'?'active':''} onClick={()=>setTab('craft')}>⚒<span>Крафт</span></button><button className={tab==='market'?'active':''} onClick={()=>setTab('market')}>◇<span>Маркет</span></button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>◉<span>Профиль</span></button></nav>
 {modal==='wallet'&&<Modal close={()=>setModal(null)}><h2>Пополнение</h2><p>100 монет = 250 коинов Telegram</p><div className="payment">🪙 <b>100</b><span>250 коинов</span></div><p className="muted">Демонстрационный экран: оплата не подключена и средства не списываются.</p><button className="primary" onClick={()=>setModal(null)}>Понятно</button></Modal>}
 {modal==='admin'&&<Modal close={()=>setModal(null)}><h2>🔒 Администратор</h2><input id="adminpass" type="password" placeholder="Введите пароль"/><button className="primary" onClick={async()=>{try{const password=(document.getElementById('adminpass') as HTMLInputElement).value;const r=await api('/api/admin/login',{method:'POST',body:JSON.stringify({password})});setAdminToken(r.token);setModal(null);setTab('admin')}catch(e:any){setNotice(e.message)}}}>Войти</button></Modal>}</main>}
function Inventory({items,selected,toggle}:{items:Item[],selected:string[],toggle:(id:string)=>void}){return <section className="inventory"><h2>Ваш инвентарь <small>{selected.length}/6 выбрано</small></h2>{items.length?<div className="grid">{items.map(x=><button className={'skin '+(selected.includes(x.id)?'selected':'')} onClick={()=>toggle(x.id)} key={x.id}><img src={x.skin.imageUrl}/><b>{x.skin.name}</b><Price value={x.skin.price}/></button>)}</div>:<div className="empty">Здесь появятся полученные скины.</div>}</section>}
function SkinCard({skin}:{skin:Skin}){return <article className="skin"><img src={skin.imageUrl}/><small>{skin.rarity}</small><b>{skin.name}</b><Price value={skin.price}/></article>}
function Profile({user,items,sell,promo,wallet,admin,notice}:{user:User|null;items:Item[];sell:(id:string)=>void;promo:(x:string)=>void;wallet:()=>void;admin:()=>void;notice:(x:string)=>void}){const [code,setCode]=useState('');return <section className="screen profile"><button className="lock" onClick={admin}>🔒</button><div className="profile-head">{user?.avatarUrl?<img src={user.avatarUrl}/>:<div className="avatar">{user?.displayName?.[0]||'G'}</div>}<div><h2>{user?.displayName||'Загрузка...'}</h2><p>@{user?.username||'telegram_user'}</p><Price value={user?.balance||0}/></div></div><div className="action-row"><button className="primary" onClick={wallet}>Пополнить</button><button>Топ</button><button>Дроп</button></div><div className="panel"><h3>Промокод</h3><div className="input-row"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Введите код"/><button onClick={()=>{promo(code);setCode('')}}>Активировать</button></div></div><div className="inventory"><div className="section-line"><h2>Мои скины</h2><button onClick={()=>notice('Вывод временно недоступен.')}>Вывести</button></div><div className="grid">{items.map(x=><article className="skin" key={x.id}><img src={x.skin.imageUrl}/><small>{x.skin.rarity}</small><b>{x.skin.name}</b><Price value={x.skin.price}/><button className="sell" onClick={()=>sell(x.id)}>Продать</button></article>)}</div></div></section>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button>{children}</div></div>}
function Admin({token,close,reload,notice}:{token:string;close:()=>void;reload:()=>void;notice:(x:string)=>void}){const [section,setSection]=useState<'skins'|'promos'>('skins');const [all,setAll]=useState<Skin[]>([]);const [promos,setPromos]=useState<any[]>([]);const [form,setForm]=useState<any>({name:'',price:'',imageUrl:'',description:'',rarity:'Common',craftWeight:100,active:true,craftEnabled:true});const [promo,setPromo]=useState<any>({code:'',reward:'',usageLimit:1,active:true});const load=async()=>{try{setAll(await api('/api/admin/skins',{},token));setPromos(await api('/api/admin/promos',{},token))}catch(e:any){notice(e.message)}};useEffect(()=>{load()},[]);
 const saveSkin=async()=>{try{await api('/api/admin/skins',{method:'POST',body:JSON.stringify({...form,price:+form.price,craftWeight:+form.craftWeight})},token);notice('Скин добавлен');setForm({...form,name:'',price:'',imageUrl:''});load();reload()}catch(e:any){notice(e.message)}};
 const savePromo=async()=>{try{await api('/api/admin/promos',{method:'POST',body:JSON.stringify({...promo,reward:+promo.reward,usageLimit:+promo.usageLimit})},token);notice('Промокод создан');setPromo({...promo,code:'',reward:''});load()}catch(e:any){notice(e.message)}};
 return <section className="screen admin"><div className="section-line"><h2>Админ-панель</h2><button onClick={close}>Готово</button></div><div className="tabs"><button className={section==='skins'?'active':''} onClick={()=>setSection('skins')}>Скины и крафт</button><button className={section==='promos'?'active':''} onClick={()=>setSection('promos')}>Промокоды</button></div>{section==='skins'?<><div className="panel form"><h3>Новый скин</h3><input placeholder="Название" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="number" placeholder="Стоимость (монеты)" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="URL фотографии" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/><input placeholder="Редкость" value={form.rarity} onChange={e=>setForm({...form,rarity:e.target.value})}/><input type="number" placeholder="Вес выпадения" value={form.craftWeight} onChange={e=>setForm({...form,craftWeight:e.target.value})}/><textarea placeholder="Описание" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary" onClick={saveSkin}>Создать скин</button></div><div className="admin-list">{all.map(s=><div key={s.id}>{s.name} · <Price value={s.price}/> · вес {s.craftWeight}<button onClick={async()=>{await api(`/api/admin/skins/${s.id}`,{method:'PATCH',body:JSON.stringify({active:!s.active})},token);load();reload()}}>{s.active?'Отключить':'Включить'}</button></div>)}</div></>:<><div className="panel form"><h3>Новый промокод</h3><input placeholder="Код" value={promo.code} onChange={e=>setPromo({...promo,code:e.target.value})}/><input type="number" placeholder="Награда" value={promo.reward} onChange={e=>setPromo({...promo,reward:e.target.value})}/><input type="number" placeholder="Количество использований" value={promo.usageLimit} onChange={e=>setPromo({...promo,usageLimit:e.target.value})}/><button className="primary" onClick={savePromo}>Создать промокод</button></div><div className="admin-list">{promos.map(p=><div key={p.id}><b>{p.code}</b> · {p.reward} 🪙 · осталось {p.usageLimit-p.usesCount} · {p.active?'активен':'выключен'}</div>)}</div></>}</section>}
createRoot(document.getElementById('root')!).render(<App/>);
